### ISSUE TITLE
peer set up of the kanban board with my partner

### ISSUE THREAD

**Issue by nickemma** [NickEmma/capstone-project-kanban#21]
we set up the kanban board in the github project.
https://github.com/NickEmma/capstone-project-kanban/projects/1
we are a team of two people
@NickEmma student A
@ademibowale student B

**Comment by dasileker** [comment]
### **Hi @NickEmma,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**

- Cards are correctly added.



## Required Changes ♻️
_Check the comments under the review._

- Please attribute team members to your cards as the requirement says.

![Capture web_25-7-2022_131224_gitlab com](https://user-images.githubusercontent.com/61562626/180805902-fc0de79b-e712-4f48-859d-81d8b8bf0c3c.jpeg)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by nickemma** [comment]
We want those path left empty to be a group task @dasileker

**Comment by nickemma** [comment]
Those path left empty was decided by I and my partner to be group project

**Comment by dasileker** [comment]
> We want those path left empty to be a group task @dasileker 

Hello, it's not what you want, it's what they want, and we need too see who is going to build that task.

**Comment by FrederickMih** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
